/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiPreviewRouteImport } from './routes/api/preview'
import { Route as ApiRenderRouteImport } from './routes/api/render'
import { Route as RSplatRouteImport } from './routes/r.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderRoute = ApiRenderRouteImport.update({
  id: '/api/render',
  path: '/api/render',
  getParentRoute: () => rootRouteImport,
} as any)
const RSplatRoute = RSplatRouteImport.update({
  id: '/r/$',
  path: '/r/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/render': typeof ApiRenderRoute
  '/r/$': typeof RSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/render': typeof ApiRenderRoute
  '/r/$': typeof RSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/render': typeof ApiRenderRoute
  '/r/$': typeof RSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate' | '/api/preview' | '/api/render' | '/r/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate' | '/api/preview' | '/api/render' | '/r/$'
  id:
    '__root__' | '/' | '/api/generate' | '/api/preview' | '/api/render' | '/r/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
  ApiRenderRoute: typeof ApiRenderRoute
  RSplatRoute: typeof RSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render': {
      id: '/api/render'
      path: '/api/render'
      fullPath: '/api/render'
      preLoaderRoute: typeof ApiRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$': {
      id: '/r/$'
      path: '/r/$'
      fullPath: '/r/$'
      preLoaderRoute: typeof RSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiPreviewRoute: ApiPreviewRoute,
  ApiRenderRoute: ApiRenderRoute,
  RSplatRoute: RSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
